In [1]:
import torch.nn as nn
import torch
from torch.autograd import Variable
import math



In [2]:
class Embeddings(nn.Module):
    def __init__(self, dim, vocab_size):
        super(Embeddings,self).__init__() # == super().__init__() 
        self.lut = nn.Embedding(vocab_size,dim)
        self.d_model = dim
    
    def forward(self, x):
        return self.lut(x) * math.sqrt(self.d_model)

In [7]:
embedding = nn.Embedding(10,3)
type(embedding)


torch.nn.modules.sparse.Embedding

In [17]:
embedding.weight

Parameter containing:
tensor([[-0.6767,  0.1049,  0.6478],
        [-0.7055, -0.5302, -1.3667],
        [-0.1145, -0.2946,  0.7899],
        [-0.8218,  0.6156,  1.1165],
        [ 1.1051, -0.6456,  0.6376],
        [-0.8901, -1.2048,  0.5212],
        [ 0.3409,  0.3729,  0.1754],
        [ 1.3464, -0.0555, -1.1560],
        [-2.2071, -0.4841,  0.1326],
        [-0.7083, -0.7766, -0.9114]], requires_grad=True)

In [13]:
inputs = torch.LongTensor([[1,2,3,4],[0,6,7,8]])
inputs.shape

torch.Size([2, 4])

In [14]:
emb = embedding(inputs)

In [15]:
emb

tensor([[[-0.7055, -0.5302, -1.3667],
         [-0.1145, -0.2946,  0.7899],
         [-0.8218,  0.6156,  1.1165],
         [ 1.1051, -0.6456,  0.6376]],

        [[-0.6767,  0.1049,  0.6478],
         [ 0.3409,  0.3729,  0.1754],
         [ 1.3464, -0.0555, -1.1560],
         [-2.2071, -0.4841,  0.1326]]], grad_fn=<EmbeddingBackward0>)

In [16]:
emb.shape

torch.Size([2, 4, 3])

In [19]:
x = Variable(torch.LongTensor([[1,2,3,4],[0,6,7,8]]))

In [20]:
x

tensor([[1, 2, 3, 4],
        [0, 6, 7, 8]])

In [22]:
type(x),type(inputs)

(torch.Tensor, torch.Tensor)

In [23]:
d_model =512
vocab_size = 10000
embs = Embeddings(d_model,vocab_size= vocab_size)

In [24]:
inputs_emb = embs(x)

In [26]:
inputs_emb.shape

torch.Size([2, 4, 512])